name: "Mern-App"
services:
  api:
    container_name: node-api-container
    build:
      context: ./API-jokes
      dockerfile: Dockerfile
    image: node-api-image
    ports:
      - "5000:5000"
    env_file:
      - ./env/server.prod.env
    networks:
      - server-net
    develop:
      watch:
        - path: ./API-jokes
          action: sync
          target: /app
          ignore:
            - node_modules
  client:
    stdin_open: true
    tty: true
    container_name: react-client-container
    depends_on:
      - api
    build:
      context: ./react-client
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:5000
    image: react-client-image
    ports:
      - "3000:3000"
    networks:
      - server-net
    develop:
      watch:
        - path: ./react-client
          action: sync
          target: /app
          ignore:
            - node_modules
            - dist

networks:
  server-net:
