name: "Mern-App"
services:
  # mongodb:
  #   container_name: mongodb-container
  #   image: mongo:8.0.3
  #   volumes:
  #     - mongodb_data:/data/db
  #   env_file:
  #     - ./env/mongo.env
  #   networks:
  #     - mern-net-2
  api:
    container_name: node-api-container
    # depends_on:
    #   - mongodb
    build:
      context: ./API-jokes
      dockerfile: Dockerfile.prod
    image: node-api-image
    ports:
      - "5000:5000"
    env_file:
      - ./env/server.prod.env
    networks:
      # - mern-net-2
      - server-net
  client:
    container_name: react-client-container
    depends_on:
      - api
    build:
      context: ./react-client
      dockerfile: Dockerfile.prod
      args:
        VITE_API_BASE_URL: http://localhost:5000
    image: react-client-image
    ports:
      - "80:80"
    networks:
      - server-net

# volumes:
#   mongodb_data:
networks:
  # mern-net-2:
  server-net:
