name: "Mern-App"
services:
  mongodb:
    container_name: mongodb-container
    image: mongo:8.0.3
    volumes:
      - mongodb_data:/data/db
    env_file:
      - ./env/mongo.env
    networks:
      - mern-net-2
  api:
    container_name: node-api-container
    depends_on:
      - mongodb
    build:
      context: ./API-jokes
      dockerfile: Dockerfile
    image: node-api-image
    ports:
      - "5000:5000"
    env_file:
      - ./env/server.env
    networks:
      - mern-net-2
      - server-net
    develop:
      watch:
        - path: ./API-jokes
          action: sync
          target: /app
          ignore:
            - node_modules
  client:
    stdin_open: true
    tty: true
    container_name: react-client-container
    depends_on:
      - api
    build:
      context: ./react-client
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:5000
    image: react-client-image
    ports:
      - "3000:3000"
    networks:
      - server-net
    develop:
      watch:
        - path: ./react-client
          action: sync
          target: /app
          ignore:
            - node_modules
            - dist

volumes:
  mongodb_data:
networks:
  mern-net-2:
  server-net:
